name: example
description: Example for format.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  ansi_escape_codes: ^2.1.0
  benchmark_harness: ^2.3.1
  format:
    path: ..
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
