import 'format_reference_model.dart';

const formatReferenceStartMarker = '<!-- BEGIN GENERATED FORMAT REFERENCE -->';
const formatReferenceEndMarker = '<!-- END GENERATED FORMAT REFERENCE -->';

final class RenderedReference {
  final String markdown;
  final List<String> semanticIds;

  const RenderedReference(this.markdown, this.semanticIds);
}

RenderedReference renderFormatReference(
  FormatReferenceContract contract,
  ReferenceLanguage language,
) {
  final output = StringBuffer();
  final semanticIds = <String>[];

  void heading(String english, String russian, {int level = 3}) {
    output
      ..write('#' * level)
      ..write(' ')
      ..writeln(language == ReferenceLanguage.english ? english : russian)
      ..writeln();
  }

  void grammar(List<GrammarRule> rules) {
    output.writeln('```text');
    for (final rule in rules) {
      output.writeln(rule.syntax);
    }
    output
      ..writeln('```')
      ..writeln()
      ..writeln(
        language == ReferenceLanguage.english
            ? '| Syntax | Meaning |'
            : '| Синтаксис | Значение |',
      )
      ..writeln('|---|---|');
    for (final rule in rules) {
      semanticIds.add(rule.id);
      output.writeln(
        '| ${_code(rule.syntax)} | '
        '${_cell(rule.text.inLanguage(language))} |',
      );
    }
    output.writeln();
  }

  output
    ..writeln(
      language == ReferenceLanguage.english
          ? '## Format reference'
          : '## Справочник форматов',
    )
    ..writeln();

  heading('Brace template grammar', 'Грамматика brace-шаблона');
  grammar(
    contract.brace.grammar
        .where((rule) => rule.id != 'brace.specification')
        .where((rule) => rule.id != 'brace.custom')
        .toList(growable: false),
  );

  heading('Brace format specification', 'Спецификация brace-формата');
  grammar(
    contract.brace.grammar
        .where(
          (rule) =>
              rule.id == 'brace.specification' || rule.id == 'brace.custom',
        )
        .toList(growable: false),
  );

  heading('Brace options', 'Опции brace-формата');
  _renderOptionTable(output, semanticIds, contract.brace.options, language);

  heading('Brace presentation matrix', 'Матрица brace-представлений');
  _renderTypeTable(output, semanticIds, contract.brace, language);

  heading(
    'Printf grammar and dynamic options',
    'Грамматика printf и динамические опции',
  );
  grammar(contract.printf.grammar);
  _renderOptionTable(
    output,
    semanticIds,
    contract.printf.options.where(_isDynamicPrintfOption),
    language,
  );

  heading('Printf flag matrix', 'Матрица флагов printf');
  _renderPrintfFlagTable(output, semanticIds, contract.printf, language);

  heading('Printf conversion matrix', 'Матрица конверсий printf');
  _renderTypeTable(output, semanticIds, contract.printf, language);

  heading('Limits', 'Пределы');
  _renderRuleTable(output, semanticIds, contract.limits, language);

  heading('Error classes', 'Классы ошибок');
  _renderRuleTable(output, semanticIds, contract.errors, language);

  return RenderedReference(
    output.toString(),
    List<String>.unmodifiable(semanticIds),
  );
}

String replaceFormatReferenceBlock(String source, String generated) {
  final starts = formatReferenceStartMarker.allMatches(source).toList();
  final ends = formatReferenceEndMarker.allMatches(source).toList();
  if (starts.length != 1 ||
      ends.length != 1 ||
      starts.single.start > ends.single.start) {
    throw const FormatException(
      'expected exactly one ordered format-reference marker pair',
    );
  }

  final start = starts.single.end;
  final end = ends.single.start;
  final normalized = generated.endsWith('\n') ? generated : '$generated\n';
  return '${source.substring(0, start)}\n$normalized${source.substring(end)}';
}

Set<String> markdownHeadingAnchors(String markdown) {
  final anchors = <String>{};
  var fenced = false;
  for (final line in markdown.split('\n')) {
    if (line.trimLeft().startsWith('```')) {
      fenced = !fenced;
      continue;
    }
    if (fenced) continue;
    final match = RegExp(r'^(#{1,6})[ \t]+(.+?)\s*#*\s*$').firstMatch(line);
    if (match == null) continue;
    final heading = match.group(2)!.toLowerCase();
    final withoutAsciiPunctuation = heading.replaceAll(
      RegExp(r'''[!"#$%&'()*+,./:;<=>?@\[\\\]^_`{|}~]'''),
      '',
    );
    anchors.add(
      '#${withoutAsciiPunctuation.trim().replaceAll(RegExp(r'\s+'), '-')}',
    );
  }
  return anchors;
}

String renderFormatReferenceCases(FormatReferenceContract contract) {
  final output =
      StringBuffer()
        ..writeln(
          '// Generated by tool/generate_format_reference.dart. Do not edit.',
        )
        ..writeln(
          '// ignore_for_file: avoid_escaping_inner_quotes, '
          'lines_longer_than_80_chars, unnecessary_library_directive',
        )
        ..writeln('library;')
        ..writeln()
        ..writeln("import 'package:format/format.dart';")
        ..writeln()
        ..writeln('final class GeneratedFormatReferenceCase {')
        ..writeln('  final String id;')
        ..writeln('  final String Function() invoke;')
        ..writeln('  final String? expectedOutput;')
        ..writeln('  final Type? expectedError;')
        ..writeln()
        ..writeln('  const GeneratedFormatReferenceCase({')
        ..writeln('    required this.id,')
        ..writeln('    required this.invoke,')
        ..writeln('    this.expectedOutput,')
        ..writeln('    this.expectedError,')
        ..writeln(
          '  }) : assert((expectedOutput == null) != (expectedError == null));',
        )
        ..writeln('}')
        ..writeln()
        ..writeln('const formatReferenceBraceTypes = <String>{');

  for (final type in _bridgeTypes(contract.brace)) {
    for (final token in type.tokens) {
      if (token.isNotEmpty && !_isSymbolicTypeToken(token)) {
        output.writeln('  ${_dartString(token)},');
      }
    }
  }
  output
    ..writeln('};')
    ..writeln()
    ..writeln('const formatReferencePrintfFlags = <String, Set<String>>{');
  for (final type in _bridgeTypes(contract.printf)) {
    final flags = _printfFlagsFor(type, contract.printf.options);
    for (final token in type.tokens) {
      output
        ..write('  ${_dartString(token)}: {')
        ..write(flags.map(_dartString).join(', '))
        ..writeln('},');
    }
  }
  output
    ..writeln('};')
    ..writeln()
    ..writeln(
      'final class _ReferenceFormatter '
      'extends Formatter<Map<String, Object?>> {',
    )
    ..writeln('  const _ReferenceFormatter();')
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String get specifier => 'echo';")
    ..writeln()
    ..writeln('  @override')
    ..writeln(
      '  String format(Map<String, Object?> value, FormatOptions options) {',
    )
    ..writeln('    final payload = options.payload;')
    ..writeln(r"    return '${payload ?? ''}${payload == null ? '' : ':'}'")
    ..writeln(r"        '${value['value']}';")
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln(
      'final _referenceFormat = '
      'Format(formatters: const [_ReferenceFormatter()]);',
    )
    ..writeln()
    ..writeln('// dart format off')
    ..writeln('final formatReferenceCases = <GeneratedFormatReferenceCase>[');

  for (final conform in contract.cases) {
    output
      ..writeln('  GeneratedFormatReferenceCase(')
      ..writeln('    id: ${_dartString(conform.id)},')
      ..writeln('    invoke: () => ${conform.dartExpression},');
    switch (conform.expected) {
      case OutputOutcome(:final value):
        output.writeln('    expectedOutput: ${_dartString(value)},');
      case ErrorOutcome(:final kind):
        output.writeln('    expectedError: ${_errorType(kind)},');
    }
    output.writeln('  ),');
  }
  output
    ..writeln('];')
    ..writeln('// dart format on');
  return output.toString();
}

void _renderOptionTable(
  StringBuffer output,
  List<String> semanticIds,
  Iterable<OptionContract> options,
  ReferenceLanguage language,
) {
  output
    ..writeln(
      language == ReferenceLanguage.english
          ? '| Tokens | Meaning | Default | Applies to |'
          : '| Токены | Значение | По умолчанию | Применимо к |',
    )
    ..writeln('|---|---|---|---|');
  for (final option in options) {
    semanticIds.add(option.id);
    output.writeln(
      '| ${_tokens(option.tokens)} | '
      '${_cell(option.meaning.inLanguage(language))} | '
      '${_cell(option.defaultValue.inLanguage(language))} | '
      '${_categories(option.appliesTo, language)} |',
    );
  }
  output.writeln();
}

void _renderTypeTable(
  StringBuffer output,
  List<String> semanticIds,
  DialectContract dialect,
  ReferenceLanguage language,
) {
  output
    ..writeln(
      language == ReferenceLanguage.english
          ? '| Type | Accepts | Allowed option tokens | Result | '
              'Default precision |'
          : '| Тип | Принимает | Допустимые токены опций | Результат | '
              'Точность по умолчанию |',
    )
    ..writeln('|---|---|---|---|---|');
  for (final type in dialect.types) {
    semanticIds.add(type.id);
    final renderedTokens = _tokens(
      type.tokens,
      empty: language == ReferenceLanguage.english ? 'empty' : 'пусто',
    );
    final deepLink = type.deepLink?.inLanguage(language);
    final result = _cell(type.result.inLanguage(language));
    final linkedResult = deepLink == null ? result : '[$result]($deepLink)';
    output.writeln(
      '| $renderedTokens | ${_categories(type.accepts, language)} | '
      '${_allowedOptionTokens(type, dialect, language)} | '
      '$linkedResult | '
      '${_cell(type.defaultPrecision.inLanguage(language))} |',
    );
  }
  output.writeln();
}

void _renderPrintfFlagTable(
  StringBuffer output,
  List<String> semanticIds,
  DialectContract dialect,
  ReferenceLanguage language,
) {
  output
    ..writeln(
      language == ReferenceLanguage.english
          ? '| Flag | Allowed conversions | Meaning | Default |'
          : '| Флаг | Допустимые конверсии | Значение | По умолчанию |',
    )
    ..writeln('|---|---|---|---|');
  for (final option in dialect.options.where(
    (option) => !_isDynamicPrintfOption(option),
  )) {
    semanticIds.add(option.id);
    final conversions = <String>[];
    for (final type in dialect.types) {
      if (type.optionIds.contains(option.id)) conversions.addAll(type.tokens);
    }
    output.writeln(
      '| ${_tokens(option.tokens)} | ${_tokens(conversions)} | '
      '${_cell(option.meaning.inLanguage(language))} | '
      '${_cell(option.defaultValue.inLanguage(language))} |',
    );
  }
  output.writeln();
}

void _renderRuleTable(
  StringBuffer output,
  List<String> semanticIds,
  Iterable<GrammarRule> rules,
  ReferenceLanguage language,
) {
  output
    ..writeln(
      language == ReferenceLanguage.english
          ? '| Rule | Contract |'
          : '| Правило | Контракт |',
    )
    ..writeln('|---|---|');
  for (final rule in rules) {
    semanticIds.add(rule.id);
    output.writeln(
      '| ${_cell(rule.text.inLanguage(language))} | '
      '${_code(rule.syntax)} |',
    );
  }
  output.writeln();
}

bool _isDynamicPrintfOption(OptionContract option) =>
    option.id == 'printf.width' || option.id == 'printf.precision';

// The generated bridge is consumed as a stable parser-inventory surface. Its
// display order is intentionally independent from the documentation order;
// token membership and every flag association still come only from the
// supplied contract.
Iterable<TypeContract> _bridgeTypes(DialectContract dialect) {
  const braceOrder = [
    'brace.binary',
    'brace.character',
    'brace.decimal',
    'brace.scientific',
    'brace.fixed',
    'brace.general',
    'brace.locale_number',
    'brace.octal',
    'brace.string',
    'brace.hex',
    'brace.percent',
  ];
  const printfOrder = [
    'printf.character',
    'printf.string',
    'printf.signed',
    'printf.unsigned_decimal',
    'printf.octal',
    'printf.hex',
    'printf.hex_float',
    'printf.scientific',
    'printf.fixed',
    'printf.general',
    'printf.percent',
  ];
  final order =
      dialect.dialect == ReferenceDialect.brace ? braceOrder : printfOrder;
  final rank = {
    for (var index = 0; index < order.length; index++) order[index]: index,
  };
  final types = dialect.types.toList(growable: false)..sort(
    (left, right) => (rank[left.id] ?? order.length).compareTo(
      rank[right.id] ?? order.length,
    ),
  );
  return types;
}

String _allowedOptionTokens(
  TypeContract type,
  DialectContract dialect,
  ReferenceLanguage language,
) {
  final optionsById = {for (final option in dialect.options) option.id: option};
  final result = <String>[];
  for (final optionId in type.optionIds) {
    final option = optionsById[optionId]!;
    final excluded = type.excludedOptionTokens[optionId] ?? const [];
    final tokens = optionId == 'brace.type' ? type.tokens : option.tokens;
    final allowed = <String>[];
    for (final token in tokens) {
      if (!excluded.contains(token) && !allowed.contains(token)) {
        allowed.add(token);
      }
    }
    if (allowed.isEmpty) continue;

    final groupedTokens = <String, List<String>>{};
    final groupedCategories = <String, List<ValueCategory>>{};
    for (final token in allowed) {
      final declaredCategories =
          type.tokenAppliesTo[token] ??
          type.optionAppliesTo[optionId] ??
          option.appliesTo;
      final categories = _effectiveCategories(type, declaredCategories);
      final key = categories.map((category) => category.name).join('|');
      groupedTokens.putIfAbsent(key, () => <String>[]).add(token);
      groupedCategories[key] = categories;
    }
    for (final entry in groupedTokens.entries) {
      var rendered = _tokens(
        entry.value,
        empty: language == ReferenceLanguage.english ? 'empty' : 'пусто',
      );
      final categories = groupedCategories[entry.key]!;
      if (dialect.dialect == ReferenceDialect.brace &&
          !_categoriesCoverEveryAcceptedValue(type, categories)) {
        final qualifier = _categories(categories, language);
        rendered =
            language == ReferenceLanguage.english
                ? '$rendered ($qualifier only)'
                : '$rendered (только $qualifier)';
      }
      result.add(rendered);
    }
  }
  return result.isEmpty ? '—' : result.join('; ');
}

List<ValueCategory> _effectiveCategories(
  TypeContract type,
  List<ValueCategory> declared,
) {
  if (declared.contains(ValueCategory.any)) return type.accepts;
  if (type.accepts.contains(ValueCategory.any)) return declared;
  return declared.where(type.accepts.contains).toList(growable: false);
}

bool _categoriesCoverEveryAcceptedValue(
  TypeContract type,
  List<ValueCategory> categories,
) {
  if (categories.contains(ValueCategory.any)) return true;
  if (type.accepts.contains(ValueCategory.any)) return false;
  return type.accepts.every(categories.contains);
}

List<String> _printfFlagsFor(TypeContract type, List<OptionContract> options) {
  final result = <String>[];
  for (final option in options) {
    if (_isDynamicPrintfOption(option) || !type.optionIds.contains(option.id)) {
      continue;
    }
    result.addAll(option.tokens);
  }
  return result;
}

String _categories(
  Iterable<ValueCategory> categories,
  ReferenceLanguage language,
) => categories.map((category) => _category(category, language)).join(', ');

String _category(ValueCategory category, ReferenceLanguage language) {
  final russian = language == ReferenceLanguage.russian;
  return switch (category) {
    ValueCategory.any => russian ? 'любое значение' : 'any value',
    ValueCategory.text => '`String`',
    ValueCategory.integer => '`int`, `BigInt`',
    ValueCategory.nonNegativeInteger =>
      russian
          ? 'неотрицательные `int`, `BigInt`'
          : 'non-negative `int`, `BigInt`',
    ValueCategory.floating => '`double`',
    ValueCategory.custom => russian ? 'собственное значение' : 'custom value',
    ValueCategory.none => '—',
  };
}

String _tokens(Iterable<String> tokens, {String empty = '—'}) {
  final values = tokens.toList(growable: false);
  if (values.isEmpty) return '—';
  return values
      .map((token) => token.isEmpty ? '*$empty*' : '`${_cell(token)}`')
      .join(', ');
}

String _cell(String value) => value
    .replaceAll('|', r'\|')
    .replaceAll('\r\n', '<br>')
    .replaceAll('\n', '<br>')
    .replaceAll('\r', '<br>');

String _code(String value) {
  final escaped = _cell(value);
  return escaped.contains('`') ? '`` $escaped ``' : '`$escaped`';
}

bool _isSymbolicTypeToken(String token) =>
    token == 'ASCII name' || token == 'custom_name';

String _dartString(String value) {
  final output = StringBuffer("'");
  for (final rune in value.runes) {
    switch (rune) {
      case 0x08:
        output.write(r'\b');
      case 0x09:
        output.write(r'\t');
      case 0x0a:
        output.write(r'\n');
      case 0x0c:
        output.write(r'\f');
      case 0x0d:
        output.write(r'\r');
      case 0x24:
        output.write(r'\$');
      case 0x27:
        output.write(r"\'");
      case 0x5c:
        output.write(r'\\');
      default:
        if (rune < 0x20 || rune == 0x7f) {
          output.write('\\u{${rune.toRadixString(16)}}');
        } else {
          output.writeCharCode(rune);
        }
    }
  }
  output.write("'");
  return output.toString();
}

String _errorType(FormattingErrorKind kind) => switch (kind) {
  FormattingErrorKind.invalidFormat => 'InvalidFormatException',
  FormattingErrorKind.invalidSpecifier => 'InvalidSpecifierException',
  FormattingErrorKind.missingArgument => 'MissingFormatArgumentException',
  FormattingErrorKind.unsupportedConversion => 'UnsupportedConversionException',
  FormattingErrorKind.unsupportedValue => 'UnsupportedFormatValueException',
};
