// Generated by tool/generate_format_reference.dart. Do not edit.
// ignore_for_file: avoid_escaping_inner_quotes, lines_longer_than_80_chars, unnecessary_library_directive
library;

import 'package:format/format.dart';

final class GeneratedFormatReferenceCase {
  final String id;
  final String Function() invoke;
  final String? expectedOutput;
  final Type? expectedError;

  const GeneratedFormatReferenceCase({
    required this.id,
    required this.invoke,
    this.expectedOutput,
    this.expectedError,
  }) : assert((expectedOutput == null) != (expectedError == null));
}

const formatReferenceBraceTypes = <String>{
  'b',
  'c',
  'd',
  'e',
  'E',
  'f',
  'F',
  'g',
  'G',
  'n',
  'o',
  's',
  'x',
  'X',
  '%',
};

const formatReferencePrintfFlags = <String, Set<String>>{
  'c': {'-'},
  's': {'-'},
  'd': {'-', '+', ' ', '0'},
  'i': {'-', '+', ' ', '0'},
  'u': {'-', '0'},
  'o': {'-', '#', '0'},
  'x': {'-', '#', '0'},
  'X': {'-', '#', '0'},
  'a': {'-', '+', ' ', '#', '0'},
  'A': {'-', '+', ' ', '#', '0'},
  'e': {'-', '+', ' ', '#', '0'},
  'E': {'-', '+', ' ', '#', '0'},
  'f': {'-', '+', ' ', '#', '0'},
  'F': {'-', '+', ' ', '#', '0'},
  'g': {'-', '+', ' ', '#', '0'},
  'G': {'-', '+', ' ', '#', '0'},
  '%': {},
};

final class _ReferenceFormatter extends Formatter<Map<String, Object?>> {
  const _ReferenceFormatter();

  @override
  String get specifier => 'echo';

  @override
  String format(Map<String, Object?> value, FormatOptions options) {
    final payload = options.payload;
    return '${payload ?? ''}${payload == null ? '' : ':'}'
        '${value['value']}';
  }
}

final _referenceFormat = Format(formatters: const [_ReferenceFormatter()]);

// dart format off
final formatReferenceCases = <GeneratedFormatReferenceCase>[
  GeneratedFormatReferenceCase(
    id: 'brace.escape.output',
    invoke: () => format('{{x}}'),
    expectedOutput: '{x}',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.positional.output',
    invoke: () => format('{1}/{0}', 'a', 'b'),
    expectedOutput: 'b/a',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.lookup.output',
    invoke: () => formatWith('{user.items[1]}', named: const {'user': {'items': ['a', 'b']}}),
    expectedOutput: 'b',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.item_text.output',
    invoke: () => formatWith('{record[any key]}', named: const {'record': {'any key': 'ok'}}),
    expectedOutput: 'ok',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.item_quote.error',
    invoke: () => formatWith('{record["any key"]}', named: const {'record': {'any key': 'ok'}}),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.unicode_index.output',
    invoke: () => formatWith('{١}', positional: const ['zero', 'one']),
    expectedOutput: 'one',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.numbering.error',
    invoke: () => format('{} {0}', 1, 2),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.identifier.error',
    invoke: () => formatWith('{ name }', named: const {'name': 1}),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.convert_s.output',
    invoke: () => format('{!s}', null),
    expectedOutput: 'null',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.convert_r.output',
    invoke: () => format('{!r}', 'x'),
    expectedOutput: '\'x\'',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.convert_a.output',
    invoke: () => format('{!a}', 'é'),
    expectedOutput: '\'\\xe9\'',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.convert_unknown.error',
    invoke: () => format('{!q}', 1),
    expectedError: UnsupportedConversionException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.nested.output',
    invoke: () => format('{:{}}', 'x', 3),
    expectedOutput: 'x  ',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.nested_depth.error',
    invoke: () => format('{:{:{}}}', 'x', 3, 1),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.balanced_payload.output',
    invoke: () => _referenceFormat.format('{:echo:a{{b}}c}', const {'value': '42'}),
    expectedOutput: 'a{b}c:42',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.unbalanced_payload.error',
    invoke: () => _referenceFormat.format('{:echo:a{{b}', const {'value': '42'}),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.missing.error',
    invoke: () => format('{}'),
    expectedError: MissingFormatArgumentException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.text.output',
    invoke: () => format('{:*^5.3s}', 'abcdef'),
    expectedOutput: '*abc*',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.sign.error',
    invoke: () => format('{:+s}', 'abc'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.alternate.error',
    invoke: () => format('{:#s}', 'abc'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.text_zero.error',
    invoke: () => format('{:05s}', 'abc'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.character.output',
    invoke: () => format('{:>3c}', 65),
    expectedOutput: '  A',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.character_precision.error',
    invoke: () => format('{:.1c}', 65),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.character_value.error',
    invoke: () => format('{:c}', 0xD800),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.sign_zero.output',
    invoke: () => format('{:+08d}', 42),
    expectedOutput: '+0000042',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.alternate.output',
    invoke: () => format('{:#x}', 42),
    expectedOutput: '0x2a',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.integer_grouping.output',
    invoke: () => format('{:,d}', 1234567),
    expectedOutput: '1,234,567',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.radix_grouping.output',
    invoke: () => format('{:_x}', 0xabcdef),
    expectedOutput: 'ab_cdef',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.grouping.error',
    invoke: () => format('{:,x}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.integer_precision.error',
    invoke: () => format('{:.2d}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.negative_zero.error',
    invoke: () => format('{:zd}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.fraction_grouping.error',
    invoke: () => format('{:.,d}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.option_order.error',
    invoke: () => format('{:10+d}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.negative_zero.output',
    invoke: () => format('{:z.2f}', -0.001),
    expectedOutput: '0.00',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.fraction_grouping.output',
    invoke: () => format('{:.6_f}', 1234.5678),
    expectedOutput: '1234.567_800',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.fraction_default.output',
    invoke: () => Format(doubleFormatMode: DoubleFormatMode.compatible).format('{:.,f}', 1234.5678),
    expectedOutput: '1234.567,800',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.dart_precision.error',
    invoke: () => format('{:.22g}', 1.0),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.compatible_precision.output',
    invoke: () => Format(doubleFormatMode: DoubleFormatMode.compatible).format('{:.21f}', 0.1),
    expectedOutput: '0.100000000000000005551',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.compatible_precision_limit.output',
    invoke: () => Format(doubleFormatMode: DoubleFormatMode.compatible).format('{:.100000f}', 0.0).length.toString(),
    expectedOutput: '100002',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.compatible_precision_limit.error',
    invoke: () => Format(doubleFormatMode: DoubleFormatMode.compatible).format('{:.100001f}', 0.0),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.option_limit.output',
    invoke: () => format('{:100000d}', 1).length.toString(),
    expectedOutput: '100000',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.option_limit.error',
    invoke: () => format('{:100001d}', 1),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.fill_limit.output',
    invoke: () => Format(textUnit: TextUnit.graphemeClusters).format('{:😀>100000s}', 'x').length.toString(),
    expectedOutput: '199999',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.fill_limit.error',
    invoke: () => Format(textUnit: TextUnit.graphemeClusters).format('{:👩‍🔬>100000s}', 'x'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.index.output',
    invoke: () => formatWith('{1}', positional: const ['zero', 'one']),
    expectedOutput: 'one',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.index_max.error',
    invoke: () => formatWith('{9223372036854775807}'),
    expectedError: MissingFormatArgumentException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.index_over.error',
    invoke: () => formatWith('{9223372036854775808}'),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_explicit.output',
    invoke: () => _referenceFormat.format('{:*^10echo:tag}', const {'value': '42'}),
    expectedOutput: '**tag:42**',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_automatic.output',
    invoke: () => _referenceFormat.format('{}', const {'value': '42'}),
    expectedOutput: '42',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_value.error',
    invoke: () => _referenceFormat.format('{:echo}', 42),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_align.error',
    invoke: () => _referenceFormat.format('{:=8echo}', const {'value': '42'}),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_syntax.error',
    invoke: () => _referenceFormat.format('{:echo!bad}', const {'value': '42'}),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_missing.error',
    invoke: () => format('{:missing}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.custom_fraction.output',
    invoke: () => _referenceFormat.format('{:.,echo:tag}', const {'value': '42'}),
    expectedOutput: 'tag:42',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.none.output',
    invoke: () => format('{}', true),
    expectedOutput: 'true',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.s.output',
    invoke: () => format('{:s}', 'text'),
    expectedOutput: 'text',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.s.error',
    invoke: () => format('{:s}', 42),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.c.output',
    invoke: () => format('{:c}', BigInt.from(65)),
    expectedOutput: 'A',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.c.error',
    invoke: () => format('{:c}', 'A'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.d.output',
    invoke: () => format('{:d}', BigInt.from(42)),
    expectedOutput: '42',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.d.error',
    invoke: () => format('{:d}', '42'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.b.output',
    invoke: () => format('{:b}', 42),
    expectedOutput: '101010',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.b.error',
    invoke: () => format('{:b}', '42'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.o.output',
    invoke: () => format('{:o}', 42),
    expectedOutput: '52',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.o.error',
    invoke: () => format('{:o}', '42'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.x.output',
    invoke: () => format('{:x}', 42),
    expectedOutput: '2a',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.x.error',
    invoke: () => format('{:x}', '42'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_x.output',
    invoke: () => format('{:X}', 42),
    expectedOutput: '2A',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_x.error',
    invoke: () => format('{:X}', '42'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.n.output',
    invoke: () => format('{:n}', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.n.error',
    invoke: () => format('{:n}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.f.output',
    invoke: () => format('{:.1f}', 2),
    expectedOutput: '2.0',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.f.error',
    invoke: () => format('{:f}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_f.output',
    invoke: () => format('{:.1F}', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_f.error',
    invoke: () => format('{:F}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.e.output',
    invoke: () => format('{:.1e}', BigInt.from(12)),
    expectedOutput: '1.2e+1',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.e.error',
    invoke: () => format('{:e}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_e.output',
    invoke: () => format('{:E}', 2.5),
    expectedOutput: '2.5E+0',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_e.error',
    invoke: () => format('{:E}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.g.output',
    invoke: () => format('{:g}', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.g.error',
    invoke: () => format('{:g}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_g.output',
    invoke: () => format('{:G}', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.upper_g.error',
    invoke: () => format('{:G}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.percent.output',
    invoke: () => format('{:%}', 2.5),
    expectedOutput: '250.000000%',
  ),
  GeneratedFormatReferenceCase(
    id: 'brace.type.percent.error',
    invoke: () => format('{:%}', '2.5'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.percent.output',
    invoke: () => sprintf('x%%y'),
    expectedOutput: 'x%y',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.empty_precision.output',
    invoke: () => sprintf('%.f', 1.5),
    expectedOutput: '2',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.repeat_precedence.output',
    invoke: () => sprintf('%++ d', 42),
    expectedOutput: '+42',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.space.output',
    invoke: () => sprintf('% d', 42),
    expectedOutput: ' 42',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.zero.output',
    invoke: () => sprintf('%05d', 42),
    expectedOutput: '00042',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.left_zero.output',
    invoke: () => sprintf('%-05d', 42),
    expectedOutput: '42   ',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic.output',
    invoke: () => vsprintf('%*.*f', const [8, 2, 1.5]),
    expectedOutput: '    1.50',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.negative_width.output',
    invoke: () => vsprintf('%*s', const [-4, 'x']),
    expectedOutput: 'x   ',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.negative_precision.output',
    invoke: () => vsprintf('%.*s', const [-1, 'abc']),
    expectedOutput: 'abc',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_missing.error',
    invoke: () => vsprintf('%*s', const []),
    expectedError: MissingFormatArgumentException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_type.error',
    invoke: () => vsprintf('%*s', const ['4', 'x']),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.flag.error',
    invoke: () => sprintf('%+u', 1),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.sign_character.error',
    invoke: () => sprintf('%+c', 65),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.alternate_decimal.error',
    invoke: () => sprintf('%#d', 1),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.zero_string.error',
    invoke: () => sprintf('%05s', 'x'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.precision_character.error',
    invoke: () => sprintf('%.1c', 65),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.grammar.error',
    invoke: () => sprintf('%q', 1),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.length.error',
    invoke: () => sprintf('%llx', 1),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.position.error',
    invoke: () => sprintf(r'%2$d', 1),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.ascii_digit.error',
    invoke: () => sprintf('%١d', 1),
    expectedError: InvalidFormatException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.percent_option.error',
    invoke: () => sprintf('%1%'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.integer_precision.output',
    invoke: () => sprintf('%05.3d', 42),
    expectedOutput: '  042',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.alternate_octal.output',
    invoke: () => sprintf('%#o', 42),
    expectedOutput: '052',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.alternate_hex.output',
    invoke: () => sprintf('%#x', 42),
    expectedOutput: '0x2a',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.string_precision.output',
    invoke: () => sprintf('%.3s', 'abcdef'),
    expectedOutput: 'abc',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.option_limit.output',
    invoke: () => sprintf('%100000d', 1).length.toString(),
    expectedOutput: '100000',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.option_limit.error',
    invoke: () => sprintf('%100001d', 1),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.precision_limit.output',
    invoke: () => sprintf('%.100000s', 'x'),
    expectedOutput: 'x',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.precision_limit.error',
    invoke: () => sprintf('%.100001s', 'x'),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_width_limit.output',
    invoke: () => vsprintf('%*s', const [100000, 'x']).length.toString(),
    expectedOutput: '100000',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_width_lower.output',
    invoke: () => vsprintf('%*s', const [-100000, 'x']).length.toString(),
    expectedOutput: '100000',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_limit.error',
    invoke: () => vsprintf('%*s', const [100001, 'x']),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_width_lower.error',
    invoke: () => vsprintf('%*s', const [-100001, 'x']),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_precision_limit.output',
    invoke: () => vsprintf('%.*s', const [100000, 'x']),
    expectedOutput: 'x',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.dynamic_precision_limit.error',
    invoke: () => vsprintf('%.*s', const [100001, 'x']),
    expectedError: InvalidSpecifierException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.value_missing.error',
    invoke: () => vsprintf('%d %s', const [1]),
    expectedError: MissingFormatArgumentException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.s.output',
    invoke: () => sprintf('%s', true),
    expectedOutput: 'true',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.c.output',
    invoke: () => sprintf('%c', BigInt.from(65)),
    expectedOutput: 'A',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.c.error',
    invoke: () => sprintf('%c', 'A'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.d.output',
    invoke: () => sprintf('%d', BigInt.from(-42)),
    expectedOutput: '-42',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.d.error',
    invoke: () => sprintf('%d', '42'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.i.output',
    invoke: () => sprintf('%i', -42),
    expectedOutput: '-42',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.i.error',
    invoke: () => sprintf('%i', '42'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.u.output',
    invoke: () => sprintf('%u', 42),
    expectedOutput: '42',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.u.error',
    invoke: () => sprintf('%u', -1),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.o.output',
    invoke: () => sprintf('%o', 42),
    expectedOutput: '52',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.o.error',
    invoke: () => sprintf('%o', -1),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.x.output',
    invoke: () => sprintf('%x', 42),
    expectedOutput: '2a',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.x.error',
    invoke: () => sprintf('%x', -1),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_x.output',
    invoke: () => sprintf('%X', 42),
    expectedOutput: '2A',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_x.error',
    invoke: () => sprintf('%X', -1),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.f.output',
    invoke: () => sprintf('%f', 2.5),
    expectedOutput: '2.500000',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.f.error',
    invoke: () => sprintf('%f', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_f.output',
    invoke: () => sprintf('%F', 2.5),
    expectedOutput: '2.500000',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_f.error',
    invoke: () => sprintf('%F', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.e.output',
    invoke: () => sprintf('%e', 2.5),
    expectedOutput: '2.5e+0',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.e.error',
    invoke: () => sprintf('%e', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_e.output',
    invoke: () => sprintf('%E', 2.5),
    expectedOutput: '2.5E+0',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_e.error',
    invoke: () => sprintf('%E', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.g.output',
    invoke: () => sprintf('%g', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.g.error',
    invoke: () => sprintf('%g', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_g.output',
    invoke: () => sprintf('%G', 2.5),
    expectedOutput: '2.5',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_g.error',
    invoke: () => sprintf('%G', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.a.output',
    invoke: () => sprintf('%a', 2.5),
    expectedOutput: '0x1.4p+1',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.a.error',
    invoke: () => sprintf('%a', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_a.output',
    invoke: () => sprintf('%A', 2.5),
    expectedOutput: '0X1.4P+1',
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.upper_a.error',
    invoke: () => sprintf('%A', '2.5'),
    expectedError: UnsupportedFormatValueException,
  ),
  GeneratedFormatReferenceCase(
    id: 'printf.type.percent.output',
    invoke: () => sprintf('%%', 1),
    expectedOutput: '%',
  ),
];
// dart format on
