#!/usr/bin/env python3
"""Generate Python's identifier and decimal-digit tables for the Dart parser."""

from __future__ import annotations

from pathlib import Path
import sys
import unicodedata


OUTPUT = Path(__file__).resolve().parents[1] / "lib" / "src" / "python_identifier.dart"
MAX_SCALAR = 0x10FFFF


def scalar_ranges(values: list[int]) -> list[tuple[int, int]]:
    if not values:
        return []
    result: list[tuple[int, int]] = []
    start = previous = values[0]
    for value in values[1:]:
        if value == previous + 1:
            previous = value
            continue
        result.append((start, previous))
        start = previous = value
    result.append((start, previous))
    return result


def decimal_ranges(values: list[tuple[int, int]]) -> list[tuple[int, int, int]]:
    if not values:
        return []
    result: list[tuple[int, int, int]] = []
    start, previous, first_value = values[0][0], values[0][0], values[0][1]
    for scalar, value in values[1:]:
        if scalar == previous + 1 and value == first_value + scalar - start:
            previous = scalar
            continue
        result.append((start, previous, first_value))
        start, previous, first_value = scalar, scalar, value
    result.append((start, previous, first_value))
    return result


def render_ranges(name: str, ranges: list[tuple[int, int]], width: int = 4) -> str:
    rows = []
    for offset in range(0, len(ranges), width):
        entries = ", ".join(
            f"0x{start:x}, 0x{end:x}" for start, end in ranges[offset : offset + width]
        )
        rows.append(f"  {entries},")
    return f"const List<int> {name} = <int>[\n" + "\n".join(rows) + "\n];"


def render_decimal_ranges(ranges: list[tuple[int, int, int]]) -> str:
    rows = []
    for offset in range(0, len(ranges), 3):
        entries = ", ".join(
            f"0x{start:x}, 0x{end:x}, {value}"
            for start, end, value in ranges[offset : offset + 3]
        )
        rows.append(f"  {entries},")
    return "const List<int> _pythonDecimalRanges = <int>[\n" + "\n".join(rows) + "\n];"


def main() -> None:
    start = []
    continue_ = []
    decimals = []
    for scalar in range(MAX_SCALAR + 1):
        character = chr(scalar)
        if character.isidentifier():
            start.append(scalar)
        if ("A" + character).isidentifier():
            continue_.append(scalar)
        decimal = unicodedata.decimal(character, None)
        if decimal is not None:
            decimals.append((scalar, decimal))

    header = (
        "// GENERATED CODE - DO NOT MODIFY BY HAND.\n"
        "// Generated by tool/generate_python_identifiers.py with "
        f"Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro} "
        f"and Unicode {unicodedata.unidata_version}.\n\n"
        "part of 'engine.dart';\n\n"
    )
    helpers = """
bool isPythonIdentifierStart(int scalar) =>
    _containsPythonRange(_pythonIdentifierStartRanges, scalar);

bool isPythonIdentifierContinue(int scalar) =>
    _containsPythonRange(_pythonIdentifierContinueRanges, scalar);

int? pythonDecimalDigitValue(int scalar) {
  var lower = 0;
  var upper = _pythonDecimalRanges.length ~/ 3 - 1;
  while (lower <= upper) {
    final middle = (lower + upper) ~/ 2;
    final base = middle * 3;
    final start = _pythonDecimalRanges[base];
    final end = _pythonDecimalRanges[base + 1];
    if (scalar < start) {
      upper = middle - 1;
    } else if (scalar > end) {
      lower = middle + 1;
    } else {
      return _pythonDecimalRanges[base + 2] + scalar - start;
    }
  }
  return null;
}

bool _containsPythonRange(List<int> ranges, int scalar) {
  var lower = 0;
  var upper = ranges.length ~/ 2 - 1;
  while (lower <= upper) {
    final middle = (lower + upper) ~/ 2;
    final base = middle * 2;
    final start = ranges[base];
    final end = ranges[base + 1];
    if (scalar < start) {
      upper = middle - 1;
    } else if (scalar > end) {
      lower = middle + 1;
    } else {
      return true;
    }
  }
  return false;
}
""".lstrip()
    content = "\n\n".join(
        [
            header.rstrip(),
            "// dart format off",
            render_ranges("_pythonIdentifierStartRanges", scalar_ranges(start)),
            render_ranges("_pythonIdentifierContinueRanges", scalar_ranges(continue_)),
            render_decimal_ranges(decimal_ranges(decimals)),
            "// dart format on",
            helpers.rstrip(),
        ]
    ) + "\n"
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
